fix: allow examples to be multiline
scalar/scalar pull request #1225
Opened 2024-03-18 23:07 UTC by hwkr

Moves the examples below the description allowing them to be multiline.

This isn't a perfect solution but @cameronrohani want's to do an overhaul of the model design soon so this just a basic fix. If people complain about it making the page longer or whatever we can always make it fancier later.

### Before:

![Google Chrome-2024-03-18-16-07-10@2x](https://github.com/scalar/scalar/assets/6374090/961c7390-0739-46bb-8fa0-bdff50a83162)

### After:

<img alt="Google Chrome-2024-03-18-16-06-36@2x" src="https://github.com/scalar/scalar/assets/6374090/9e710c5a-2be5-4a27-b903-d05bc0520689">

2024-03-18 23:09 UTC, hanspagel commented
Love it!

2024-03-19 01:02 UTC, marclave requested changes
nice!

could we add a max height to these examples and make it scrollable like how we do in the response + request examples

<img width="579" alt="image" src="https://github.com/scalar/scalar/assets/6176314/2e402d14-88d0-4e7e-b29a-01b0c95b9c8a">

2024-03-19 05:53 UTC, hwkr commented
This PR also seems to have broken the Show More button, I'm not sure how but I'll debug tomorrow...

2024-03-19 23:47 UTC, hwkr commented
@marclave scrolling added 👍 

https://github.com/scalar/scalar/assets/6374090/22396ed1-8810-4b37-8881-2a9cf2d0dd53

2024-03-20 04:31 UTC, marclave commented
Testing now!

2024-03-20 15:52 UTC, marclave approved these changes
✨ nice 😎

2024-03-20 15:52 UTC, merged