fix: buffer not available in browser environments, fix #1272
scalar/scalar pull request #1277
Opened 2024-03-21 20:26 UTC by hanspagel

We recently remove all Node polyfills. Unfortunately, we still need a polyfill for `Buffer`, which is not available in browser environments. :(

See #1272

2024-03-21 21:49 UTC, amritk requested changes
@hanspagel instead of adding a polyfill try btoa instead of buffer in the browser
a little something like this:
```ts
if (typeof window === 'undefined') {
   Buffer.from(`${username}:${password}`).toString('base64') 
}
else {
  btoa(`${username}:${password}`);
}
```
btoa(`${username}:${password}`);

2024-03-21 23:02 UTC, geoffgscott requested changes
@hanspagel We can use btoa() for this purpose in Browser environments and not require the polyfill.

2024-03-21 23:06 UTC, amritk commented
@geoffgscott did u just copy paste my comment? 😆

2024-03-22 00:09 UTC, hanspagel commented
OMG, totally forgot about btoa

2024-03-22 00:09 UTC, hanspagel commented
OMG, totally forgot about btoa

2024-03-22 00:11 UTC, amritk approved these changes
<img src="https://media1.giphy.com/media/cdNSp4L5vCU7aQrYnV/giphy.gif"/>

2024-03-22 01:00 UTC, marclave approved these changes
awesome work @hanspagel !

2024-03-22 01:01 UTC, merged