refactor: rename all oss variables to be `--scalar-*`
scalar/scalar pull request #1372
Opened 2024-04-03 22:33 UTC by hwkr

I'd like to apologize in advance for any of the weird little bugs I may have introduced. Doing a change like this is a little wild.

Updated now with a migration tool and console warning if you have old console variables.

https://github.com/scalar/scalar/assets/6374090/8258f066-d953-4cd4-885b-7132f2d4561a

2024-04-09 20:56 UTC, marclave requested changes
child attributes is missing styles:

<img width="562" alt="image" src="https://github.com/scalar/scalar/assets/6176314/561b8d34-402a-4e7d-92af-7a685ee00e70">

2024-04-09 20:58 UTC, amritk approved these changes
<img src="https://media1.giphy.com/media/z0zTHzcwM4VYQ/giphy.gif"/>

Looks fine to my rookie eyes

2024-04-09 20:59 UTC, marclave requested changes
code block is missing styles for url

current
<img width="560" alt="image" src="https://github.com/scalar/scalar/assets/6176314/12080c62-e216-4e9c-8842-4c6148a5ad5c">


incorrect
<img width="552" alt="image" src="https://github.com/scalar/scalar/assets/6176314/43609537-dae3-418a-8a91-fbc20ab3eb9c">

2024-04-09 21:00 UTC, marclave commented
looks like several fonts are off

this pr
<img width="637" alt="image" src="https://github.com/scalar/scalar/assets/6176314/1f920763-1204-4b83-be04-500074b84a02">

vs

main
<img width="631" alt="image" src="https://github.com/scalar/scalar/assets/6176314/2c116723-d2f4-4dc7-90b0-0bd56c4619ed">

2024-04-09 21:01 UTC, marclave commented
api client modal has transparent body at bottom

this pr
<img width="616" alt="image" src="https://github.com/scalar/scalar/assets/6176314/e08ff02a-dea4-4aec-9309-726321d68eb6">

vs main
<img width="603" alt="image" src="https://github.com/scalar/scalar/assets/6176314/98d0300a-f341-4e6c-b689-d8390b53e58e">

2024-04-09 21:05 UTC, marclave commented
response description font is off

pr
<img width="548" alt="image" src="https://github.com/scalar/scalar/assets/6176314/b0aa227e-5d24-41a2-8f04-639f2f68e969">

vs main
<img width="560" alt="image" src="https://github.com/scalar/scalar/assets/6176314/d7456933-1e7a-4edb-8513-679af2814b23">

2024-04-09 21:07 UTC, marclave commented
tag description in classic layout is incorrect

pr
<img width="1163" alt="image" src="https://github.com/scalar/scalar/assets/6176314/f9ce59f6-7a0b-43ec-85ff-be4734fccdda">


vs main
<img width="1155" alt="image" src="https://github.com/scalar/scalar/assets/6176314/2d552ac1-3b38-4b54-b0e1-8e5c33dc598d">

2024-04-09 22:08 UTC, hwkr commented
Alrighty fixed the issues @marclave found, thank you for finding those 🙏 

You can see the changes here, one was a broken line of CSS that wasn't being applied on main and the other one was a default var that was different from the theme var (which can't happen anymore! yay!)

I wasn't able to replicate the issue with the API client body, might need a hand with that.

![Google Chrome-2024-04-09-15-06-19@2x](https://github.com/scalar/scalar/assets/6374090/3ba37c12-b6b3-47a9-ba83-a402d75ba49b)

2024-04-09 22:12 UTC, hwkr commented on packages/api-reference/src/components/MarkdownRenderer/MarkdownRenderer.vue
> -  font-size: var(
This font size rule wasn't actually being applied anywhere

2024-04-18 17:20 UTC, marclave approved these changes
:)

2024-04-18 17:20 UTC, merged