feat: cdn custom header example
scalar/scalar pull request #1775
Opened 2024-05-17 22:24 UTC by hwkr

Another swing at making it easier to add a header to the CDN references. The main change here is that we add `display: flex;` and `min-height: 0;` to the injected references container which should make it easier to add elements around it and _shouldn't_ break anyones layouts (probably).

<img width="1431" alt="Google Chrome-2024-05-17-15-47-15@2x" src="https://github.com/scalar/scalar/assets/6374090/467e65d7-bc7c-40a6-9e18-b462e8e52809">

2024-05-17 22:25 UTC, hwkr commented on examples/cdn-api-reference/src/public/api-reference-cdn-localhost.html
> +    <script src="http://localhost:5053/reference/@scalar/fastify-api-reference/js/browser.js"></script>
This seems to have been broken at some point.

2024-05-17 22:38 UTC, amritk approved these changes
Shouldn't we ALWAYS be flexin?

2024-06-19 15:09 UTC, hanspagel requested changes
This is great! When testing it like this:

```bash
pnpm --filter @scalar-examples/cdn-api-reference dev
```

<http://127.0.0.1:3173/api-reference-local-header.html>

I see double scrollbars, though. That’s not how it’s supposed to look, is it?

<img width="1503" alt="Screenshot 2024-06-19 at 17 07 35" src="https://github.com/scalar/scalar/assets/1577992/bef007d5-491d-4f6d-95fe-93d7a897fcc5">

2024-06-21 19:03 UTC, marclave commented
closed in favour of https://github.com/scalar/scalar/pull/2198

2024-06-21 19:03 UTC, closed without merging