fix: HMR doesn’t work in examples/web
scalar/scalar pull request #1909
Opened 2024-05-30 14:39 UTC by hanspagel

With #1765 the resolve alias was removed from `examples/web`, this broke HMR. I think it was removed because the aliases broke for @scalar/api-reference/style.css and @scalar/api-client/style.css (we only had an exemption for @scalar/components/style.css)

This PR re-introduces the aliases and changes them to *not* match `@scalar/${anything}/style.css`.

Let’s test the deploy preview to see if the CSS is still fine and all.

2024-05-31 02:36 UTC, amritk commented
Actually it was removed on purpose! Just so we can test the packages properly since they behave differently with the alias, it was hiding some bugs. I think we should just have two vite configs one for dev and one for actual testing. What do you think @hanspagel?

2024-05-31 20:24 UTC, hanspagel commented
@amritk sounds good. can we merge this though? And follow with the testing config?

2024-05-31 20:34 UTC, amritk commented
Sure but just remember that this aliasing hides bugs sometimes

2024-06-05 05:55 UTC, amritk requested changes
This PR is no longer relevant with #1940, we'll come up with another strategy

2024-06-05 12:33 UTC, closed without merging