feat(client-app): sidebar toggle hotkey
scalar/scalar pull request #2145
Opened 2024-06-18 13:46 UTC by antlio

currently we have to key up and key down both keys in order to toggle the sidebar, however sometimes we might keep the meta key down to have a glimpse on the navigation.

this pr is a proposal to favor useEventListener over whenever, i haven't been able to reach the same result otherwise.

2024-06-19 00:11 UTC, amritk approved these changes
What were you thinking on meta press? a modal which shows all of the hotkeys?

2024-06-19 00:11 UTC, amritk commented on packages/client-app/src/views/Request/Request.vue
> +})
we can probably factor this into a helper later so it works everywhere

2024-06-19 00:13 UTC, amritk requested changes
Now i'm not sure anymore, ping me!

2024-06-19 00:13 UTC, amritk commented on packages/client-app/src/views/Request/Request.vue
> +})
also would be easier to change if we need to

2024-06-19 05:02 UTC, amritk approved these changes

2024-06-20 00:36 UTC, marclave approved these changes
lets test it out!

2024-06-20 00:36 UTC, merged