docs: add a detailed Next.js integration guide
scalar/scalar pull request #2160
Opened 2024-06-18 21:52 UTC by hanspagel

I was testing the Next.js integration today and used the opportunity to write a detailed integration guide.

@amritk I’m not really sure I did a good job describing what to use when, would you mind to check it’s not completely off?

2024-06-18 23:45 UTC, marclave approved these changes

2024-06-19 00:14 UTC, amritk approved these changes
😅 haha didn't need to explain how to install next, but doesn't hurt! This will change once we build an integration anyway.

2024-06-19 00:15 UTC, amritk requested changes
Actually can we specify app router for the top example, then page router for the bottom? not quite clear

2024-06-19 00:15 UTC, amritk commented on documentation/nextjs.md
> +… and add a new app route:
```suggestion
### App router

… and add a new app route:
```

2024-06-19 00:15 UTC, amritk commented on documentation/nextjs.md
> +
```suggestion

### Page router

```

2024-06-19 11:39 UTC, merged