chore: add more docusaurus examples
scalar/scalar pull request #2170
Opened 2024-06-19 12:16 UTC by hanspagel

I was manually testing multiple ways to load an OpenAPI document in Docusaurus, but we could also just add multiple examples. :)

<img width="1501" alt="Screenshot 2024-06-19 at 14 16 08" src="https://github.com/scalar/scalar/assets/1577992/452b0a07-6e7d-49c8-a4bb-028c1562d6a5">

2024-06-19 14:18 UTC, hkosova commented
Suggestion: maybe the Docusaurus plugin should pass its `url` param (if provided) to [`useBrokenLinks().collectLink(...)`](https://docusaurus.io/docs/docusaurus-core#useBrokenLinks) so that invalid relative URLs will be reported during `docusaurus build` by Docusaurus' built-in link checker.

2024-06-19 16:51 UTC, marclave requested changes

2024-06-19 16:51 UTC, marclave commented on packages/docusaurus/src/index.ts
> -      // Check if we need to download a spec
lets make sure we dont delete this :)

2024-06-19 17:03 UTC, marclave commented
i also get these errors :) 

but seems like my comment on the loadContent was just a cached build

<img width="1512" alt="image" src="https://github.com/scalar/scalar/assets/6176314/536c612c-baa0-43ce-899a-4ab8126e9650">

2024-06-19 20:11 UTC, hanspagel commented
@marclave this one is fixed in #2159 :)

2024-06-20 09:40 UTC, hanspagel commented
> Suggestion: maybe the Docusaurus plugin should pass its `url` param (if provided) to [`useBrokenLinks().collectLink(...)`](https://docusaurus.io/docs/docusaurus-core#useBrokenLinks) so that invalid relative URLs will be reported during `docusaurus build` by Docusaurus' built-in link checker.

I love that! Unfortunately, I’m not able to get that to work properly. 😵 I’ll try to submit a separate PR for it.

2024-06-20 19:18 UTC, marclave approved these changes
🫡

2024-06-20 19:18 UTC, merged