feat: Move object-utils to rollup
scalar/scalar pull request #2289
Opened 2024-06-27 19:13 UTC by geoffgscott

Moves object utils to our standard rollup builds

2024-06-28 13:29 UTC, hanspagel commented
It’s all coming together! Let’s review and merge this on Tuesday, not before the big release today, I’d say. :v:

2024-06-28 14:09 UTC, hanspagel requested changes
There should be a `*.d.ts` file for every source file, right?

<img width="206" alt="Screenshot 2024-06-28 at 16 11 26" src="https://github.com/scalar/scalar/assets/1577992/5b3c00f4-bd22-4804-bbd0-251d29577d7f">

2024-06-28 14:10 UTC, hanspagel commented on packages/object-utils/package.json
> +    "build": "scalar-build-rollup",
We should consider to empty the dist folder in `scalar-build-rollup`. Keeping old files can be confusing when  testing locally.

2024-06-28 14:33 UTC, geoffgscott commented
> There should be a `*.d.ts` file for every source file, right?
> 
> <img alt="Screenshot 2024-06-28 at 16 11 26" width="206" src="https://private-user-images.githubusercontent.com/1577992/344197385-5b3c00f4-bd22-4804-bbd0-251d29577d7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODUzMDMsIm5iZiI6MTcxOTU4NTAwMywicGF0aCI6Ii8xNTc3OTkyLzM0NDE5NzM4NS01YjNjMDBmNC1iZDIyLTQ4MDQtYmJkMC0yNTFkMjk1NzdkN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMTQzMDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjllZmNiNzliMDlhYmYyNTI2MjcyMTZmZTI3ZDczMGE0YTVjOTg0MGUxZDNmMmEzNWU5OTcwNWZmMzU0YTAyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jYWkS5zyj5TU9SYt-H54L7GenLuxG49z9z92MfCd8gs">

Yes and it is:
![image](https://github.com/scalar/scalar/assets/59206100/54f0cec1-0214-43bd-995a-d4954fd6b6c1)


These commands are not new they have been in use for several weeks now so nothing should change between packages (unless the original tsconfig file had issues)

2024-06-28 14:35 UTC, hanspagel commented
Ah, I didn’t execute `types:build`, I thought that happens with `build`, too. :v:

2024-06-28 14:35 UTC, hanspagel approved these changes

2024-06-28 14:40 UTC, geoffgscott commented
> Ah, I didn’t execute `types:build`, I thought that happens with `build`, too. ✌️

It does execute as part of `scalar-build-rollup`. It's not auto-deleting the dist right now though so maybe you just had extra files in there.

2024-07-02 04:04 UTC, marclave approved these changes

2024-07-02 04:05 UTC, merged