feat: add pre/post request scripts
scalar/scalar pull request #2420
Opened 2024-07-07 20:23 UTC by marclave

🚨 new feature alert 🚨 

Scripting in the Scalar API Client : ) it's pure javascript, with access to a `scalar` object, with some namespaces for functionality depending on if you are in the pre or post script sections

**Present**
Pre Request:
- can access the `request` and add headers : ) (do we give access to the AxiosConfig and let users modify or slight helpers like i did here?)

Post Request:
- tests! you can now run tests and expect values : )
- you also get access to the `response` object to check whats going on : )

![image](https://github.com/scalar/scalar/assets/6176314/ae16d2df-7749-4f68-9dd1-5a52f555fd1b)

**Future**
- we should add the scalar object to the Codemirror config so we can add code completion + hints
- we should fix javascript script highlighting
- add a `scalar-x-scripts` OpenAPI extension so we can add these on the fly ✨ 
- Add way more test functionality (do we just use `vitest` browser only?
- This is just at the request level, but we can eventually do: Folder, Collection and workspace level : )
- We should also be able to send requests from the pre request script (foundationally request chaining 😏 )

i disabled this for the Modal mode, so we can get this merged and play around with it as we build : ) but it's pretty fun!!

2024-07-08 14:45 UTC, antlio commented
this seems to be missing some styling, need someone to jump? @marclave

2024-07-16 02:17 UTC, geoffgscott requested changes
A few changes needed. Awesome start.

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/scalarScripts.ts
> +function getPreRequestScalarObject(config: AxiosRequestConfig) {
Before we launch this let's move to vanilla fetch.

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/scalarScripts.ts
> +    toBe: (expected: any) => {
Would be nice to have user generated messages here. Should take an optional second argument that is  `(actual: any, expected: any): string`

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/scalarScripts.ts
> +    toBe: (expected: any) => {
If its provided then we should run that function to generate the message and fallback to our message

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/scalarScripts.ts
> +    sub: (a: number, b: number) => a - b,
All of these return elements need proper doc strings

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/scalarScripts.ts
> +    _testResults: testResults,
underscore is not a pattern we generally use in our codebase.

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/sendRequest.ts
>    let url = rawUrl
No `let`.

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/sendRequest.ts
> +  let config: AxiosRequestConfig = {
No let. Use object assign, objectMerge or override properties as needed.

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/sendRequest.ts
> +        console.warn('Post-send script error:', error)
Some display of these errors to the user would be sweet. Toast?

2024-07-16 02:17 UTC, geoffgscott commented on packages/api-client/src/libs/sendRequest.ts
>      const axiosError = error as AxiosError
This is a bad typecasts. Its not guaranteed to be an axios error.

2024-07-16 16:41 UTC, marclave commented
moving this to draft for now :)

2024-08-27 16:57 UTC, marclave commented
well this ticket got stale quick : ) let's re-add it back post workspace entities PR

2024-08-27 16:57 UTC, closed without merging

2025-12-11 16:14 UTC, bretthowell714-source approved these changes

2026-02-19 13:39 UTC, dastanko commented
Any specific reason why this feature is not deployed?

2026-06-12 13:43 UTC, fiverrwixs-cmyk commented on packages/api-client/src/libs/scalarScripts.ts
> +function getPreRequestScalarObject(config: AxiosRequestConfig) {
hi