feat: add colors to env vars and pills
scalar/scalar pull request #2549
Opened 2024-07-19 03:43 UTC by marclave

![image](https://github.com/user-attachments/assets/0f8df223-04cb-470e-9b30-1955bce8049c)

@cameronrohani need to touch this up

2024-07-19 17:40 UTC, amritk commented on packages/api-client/src/components/CodeInput/codeVariableWidget.ts
> +        _scalarEnvId: any
Dont think we need the _ here

2024-07-19 17:40 UTC, amritk commented on packages/api-client/src/components/CodeInput/codeVariableWidget.ts
> +        _scalarEnvId: any
or we can... I suppose lol

2024-07-19 17:42 UTC, amritk requested changes
Can we factor our this duplicated function?

2024-07-19 17:43 UTC, amritk commented on packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
> +const getEnvColor = (
looks familiar....

2024-07-19 17:55 UTC, marclave commented on packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
> +const getEnvColor = (
ohhhh yes, where should i put it?

2024-07-19 17:55 UTC, amritk commented on packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
> +const getEnvColor = (
libs

2024-07-19 18:13 UTC, marclave commented on packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
> +const getEnvColor = (
based

2024-07-21 19:06 UTC, cameronrohani approved these changes

2024-07-21 19:24 UTC, merged