feat(api-client): environment table editor
scalar/scalar pull request #2827
Opened 2024-08-09 14:46 UTC by antlio

this pr is a first attempt to move from editor only to table first for the environment page:

<img width="1467" alt="image" src="https://github.com/user-attachments/assets/62c74e4e-e163-4760-ba17-f7c319d2723c">

ℹ️ colors are not displayed here as exploration is in progress in //

2024-08-28 12:56 UTC, hanspagel requested changes
Really cool 🙌 

I get some weird behaviour when I delete a few variables and add a new one. Old variables pop up again then.

https://github.com/user-attachments/assets/361e3f05-2a45-4bc5-92e8-bd37a3c3ac59

https://github.com/user-attachments/assets/d59539ff-9f1b-42ab-bd2b-cad20bfcb65d

https://github.com/user-attachments/assets/5ae77218-295e-4360-924d-417ba7e6c1a6

2024-08-28 17:55 UTC, marclave approved these changes
can merge once the entities work get's finished ✨

2024-09-02 12:17 UTC, hanspagel commented
Blocked by #2931

2024-09-27 17:51 UTC, amritk commented
This one might be easier to just pick the files instead of rebasing

2024-10-04 16:41 UTC, antlio commented
> This one might be easier to just pick the files instead of rebasing

I started this again, will push code asap in that same branch

2024-10-22 10:07 UTC, hanspagel commented
OMG, can’t believe we’re so close!

Just found some strange behaviour when two keys start the same. Did you try to attach uuids to all entries?

https://github.com/user-attachments/assets/30ba15bb-2e1c-4792-88a8-632b68cc717f

2024-10-29 23:10 UTC, hwkr commented on packages/components/src/components/ScalarIcon/icons/icons.ts
Is this replacing the `index.ts` file?

2024-10-30 05:24 UTC, antlio commented on packages/components/src/components/ScalarIcon/icons/icons.ts
good catch i guess rebase issue here 🤔 will fix!

2024-10-31 10:21 UTC, antlio commented
closing this for now - will get back to it with a better approach later on

2024-10-31 10:21 UTC, closed without merging