feat(openapi-parser): migrate openapi parser to monorepo
scalar/scalar pull request #2879
Opened 2024-08-16 01:11 UTC by tmastrom

This PR migrates the `openapi-parser` package to the monorepo

2024-08-16 19:55 UTC, marclave commented on packages/openapi-parser/pnpm-lock.yaml
@tmastrom should there be a lock file in here?

2024-08-16 19:57 UTC, marclave commented on packages/openapi-parser/src/types/openapi-types.ts
@amritk @tmastrom did we recently move types around with our new types pacakge ?

2024-08-16 20:02 UTC, amritk commented on packages/openapi-parser/src/types/openapi-types.ts
yea its been extracted, we can point this to those but we can do it in a different PR

2024-08-16 20:03 UTC, amritk commented on packages/openapi-parser/pnpm-lock.yaml
delete it!

2024-08-20 23:50 UTC, geoffgscott approved these changes
Looks good.

2024-08-26 12:11 UTC, hanspagel requested changes
Pls give me a chance to review before merging 🙏

2024-08-27 12:26 UTC, closed without merging