feat: remove `@scalar/themes` from the dependencies of `@scalar/types`
scalar/scalar pull request #3243
Opened 2024-09-25 12:19 UTC by inyourtime

#3241

2024-09-25 12:21 UTC, hanspagel requested changes
Let’s try to add types as a dependency of themes and import the ThemeId there instead of copying the type ✌️

2024-09-25 12:22 UTC, inyourtime commented
i will do it.

2024-09-25 16:47 UTC, amritk requested changes
Just requested one change to the tsconfig, but excellent work!

2024-09-25 16:47 UTC, amritk commented on packages/themes/tsconfig.json
> +    "moduleResolution": "Bundler",
hey great work! do you think you can do one better and just extend the base tsconfig?

```json
{
  "extends": "../../tsconfig.json"
}
```

2024-09-26 00:37 UTC, amritk approved these changes
LGTM!

2024-09-26 15:11 UTC, hanspagel approved these changes
Thanks so much! :) Love when the dependency tree becomes smaller/simpler.

2024-09-26 15:11 UTC, merged