feat(api-reference): add error boundaries
scalar/scalar pull request #3762
Opened 2024-11-05 14:12 UTC by hanspagel

Currently, when an error is thrown, the whole page is empty.

This PR introduces a `ScalarErrorBoundary` component, that catches errors, shows the error message, but everything else is still rendered properly.

## Before

<img width="1492" alt="Screenshot 2024-11-05 at 14 54 23" src="https://github.com/user-attachments/assets/77cbc883-1fb3-49ca-b38d-fd788efeb75a">

## After

**Base URL**

<img width="1486" alt="Screenshot 2024-11-05 at 14 59 56" src="https://github.com/user-attachments/assets/2ab1934a-3bdd-44ca-9156-de8ded9b41a1">

**Sidebar**

<img width="1485" alt="Screenshot 2024-11-05 at 14 59 31" src="https://github.com/user-attachments/assets/ffbf746a-840e-48cf-a613-e79c977ff099">

**Example Responses**

<img width="1486" alt="Screenshot 2024-11-05 at 15 02 33" src="https://github.com/user-attachments/assets/66713a85-02d6-4eb2-9b66-8683742ee84a">

**Models**

<img width="1156" alt="Screenshot 2024-11-05 at 15 00 47" src="https://github.com/user-attachments/assets/f586f72d-1a05-4836-ad47-e2cf55b53d6f">

2024-11-06 17:41 UTC, hwkr commented on packages/components/src/components/ScalarErrorBoundary/ScalarErrorBoundary.vue
I wonder if we should hide the error message in a modal or a tooltip or something

2024-11-06 17:42 UTC, hwkr commented
Looks good! Might fiddle with some of the styling with Cam if that's okay. Also wouldn't mind @amritk having a look :)

2024-11-06 21:25 UTC, amritk commented on packages/components/src/components/ScalarErrorBoundary/ScalarErrorBoundary.vue
I prefer showing the error message, much easier for sharing back to us

2024-11-06 21:26 UTC, amritk approved these changes
Exactly what I was thinking!

<img src="https://media3.giphy.com/media/UiujkYUI1GlHoj3mgl/giphy.gif"/>

2024-11-06 21:27 UTC, amritk commented
Oh also can we move it to components and use it in the client as well!?

2024-11-07 05:50 UTC, hwkr commented
Added some tests and a storybook :) Tweaked the component itself a tiny bit too but feel free to put it back.

I also tried out some other visual treatments, not sure if I like them better or not 🤔 

### With a dotted border

![Google Chrome-2024-11-06-22-38-30@2x](https://github.com/user-attachments/assets/eaa512c1-282e-4f51-85d7-1d0b221776a5)

### Using a `<details>` and including the stack
![Google Chrome-2024-11-06-22-39-14@2x](https://github.com/user-attachments/assets/0561d884-179d-4b12-a811-f257451381af)
![Google Chrome-2024-11-06-22-39-19@2x](https://github.com/user-attachments/assets/013bd654-52b3-4b02-8c97-2dad61b99f22)

2024-11-07 05:50 UTC, hwkr approved these changes

2024-11-08 12:11 UTC, hanspagel commented
Waiting for @cameronrohani ✌️

2024-11-11 18:55 UTC, cameronrohani commented
happy to spruce this up briefly, but I think @marclave had some feedback here

2024-11-12 19:29 UTC, amritk commented
Lets get it innnnn

2024-11-15 16:33 UTC, marclave requested changes
lets chat about it before merging, we might wanna just do a toast or smth?

2024-11-18 11:18 UTC, hanspagel commented
With this PR we ensure that we render as much as possible (which could be 99 % of the reference), instead of just showing a blank page because of an exception in just one component. That’s so much better than what we have and so much than a toast. HMU so I can convince you. :)

2024-11-18 22:54 UTC, amritk commented
Agreed with hans, using an error boundary component is a common practice! Used it many times before

2024-11-20 20:16 UTC, cameronrohani commented
Any updates here? 😅 

Should I style it or are we wanting to reconsider the approach?

@hanspagel @marclave 👂

2024-11-21 10:59 UTC, hanspagel commented
YESS, cool. @cameronrohani do your thing!

In theory no one should see this component, and even in reality it should only be seen by very, very few people, so I’d be OK with doing styling in another PR, but whatever works for you!

2024-11-24 17:43 UTC, marclave commented
@hanspagel should we add a cta to go to our github to open an issue?

2024-11-25 10:39 UTC, hanspagel commented
If we bork the CDN, it’s the users of our users that see it, though. Maybe we don’t want to ask _them_ to report a bug, but just trust our users to find their way in that case.

2024-11-26 14:30 UTC, marclave approved these changes

2024-11-26 15:14 UTC, merged

2024-11-27 04:35 UTC, hwkr commented
What happened to the tests 😭

2024-11-27 04:36 UTC, hwkr commented
Oh no did I not push them 🤦