fix: use base server URL in the client
scalar/scalar pull request #3776
Opened 2024-11-06 00:03 UTC by amritk

closes #3606

This is what we wanted right @hanspagel ?

2024-11-06 00:04 UTC, amritk commented on packages/api-reference/src/features/BaseUrl/ServerForm.vue
> +    <label class="server-form-title">Server URL</label>
I also renamed Base URL -> Server URL in the UI so there's less confusion.

2024-11-06 09:28 UTC, hanspagel commented
I think it doesn’t work in the references aswell, need to test later. ✌️

2024-11-06 12:59 UTC, hanspagel commented
Okay, it works in the reference, but not in the client.

**OpenAPI document**
```json
        {
            "openapi": "3.1.0",
            "info": {
                "title": "Hello World",
                "version": "1.0.0",
            },
            "servers": [{
                    "url": "/"
                },
            ],
            "paths": {
                "/foobar": {
                    "get": {
                        "operationId": "getAllData",
                        "responses": {
                            "200": {
                                "description": "OK",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                          "type": "object",
                                          "properties": {
                                              "message": {
                                                  "type": "string",
                                                  "example": "Hello World"
                                              }
                                          }
                                        }
                                    }
                                }
                            }
                        }
                    },
                },
            },
        }
```

**Configuration**

```js
{
    baseServerURL: 'https://something-custom.scalar.com',
}
```

**Result**

✅ 

<img width="570" alt="Screenshot 2024-11-06 at 13 59 13" src="https://github.com/user-attachments/assets/369da9fb-8376-432d-9f63-6ef792a3b541">

❌

<img width="826" alt="Screenshot 2024-11-06 at 13 59 16" src="https://github.com/user-attachments/assets/dd8c3fd3-54ac-4a90-9451-15a75192d2a2">

2024-11-06 18:01 UTC, amritk commented
@hanspagel ur right, I swear it was working before 😓

2024-11-06 18:16 UTC, amritk commented
alright @hanspagel fixed! maybe I dropped some changes before 🤷🏾

2024-11-07 10:57 UTC, hanspagel requested changes
This is great and we’re so close! But for some reason it has only one slash. 🙈

<img width="427" alt="Screenshot 2024-11-07 at 11 56 30" src="https://github.com/user-attachments/assets/272a387d-3aa4-44fb-9183-fb0c5968fe8c">

<img width="620" alt="Screenshot 2024-11-07 at 11 57 22" src="https://github.com/user-attachments/assets/7e1f3a64-fe81-4d83-8b28-0e1ba5bfd3fc">

2024-11-07 18:06 UTC, amritk commented
Hahaha duh I'm stupid

2024-11-07 19:00 UTC, amritk commented
@hanspagel alright this is the one, tests have been added!

2024-11-08 00:52 UTC, marclave approved these changes

2024-11-08 00:52 UTC, merged