feat(api-client): clear drafts
scalar/scalar pull request #3783
Opened 2024-11-06 08:49 UTC by antlio

this pr adds the clear drafts capability from request sidebar draft collection, as seen below:

https://github.com/user-attachments/assets/d9b48bc6-2cfb-477b-95c6-c9ca17f2f9eb

we might want to set a more central empty state in the view afterward.

2024-11-06 09:30 UTC, antlio commented
> This is so great! But didn’t we have to have at least one request for some reason? 🤔

We do on the first usage of the client, no strong opinion about if we should always maintain one or not

2024-11-06 11:31 UTC, hanspagel approved these changes
I’d say it’s cool, but I’ll leave this up to @marclave and @amritk.

2024-11-06 19:07 UTC, amritk requested changes
I think just create the initial my first request draft and route to it so you don't need an empty state. Either that or an empty state. Seems strange to have it blank

2024-11-08 01:00 UTC, marclave commented
> I think just create the initial my first request draft and route to it so you don't need an empty state. Either that or an empty state. Seems strange to have it blank

yes : )

2024-11-08 14:06 UTC, antlio commented
> I think just create the initial my first request draft and route to it so you don't need an empty state. Either that or an empty state. Seems strange to have it blank

I added a fallback in order to always have a first draft requests. drafts requests can be cleared in other requests are existing in the workspace, however in case of all requests being deleted, a first request is added back to the draft collection.

2024-11-12 19:29 UTC, amritk approved these changes
<img src="https://media3.giphy.com/media/4Ivaq5OHdKovVV9KCz/giphy.gif"/>

2024-11-13 12:41 UTC, merged