feat(api-client): make auth spec compliant + removal of example auth
scalar/scalar pull request #3882
Opened 2024-11-14 06:34 UTC by amritk

### Whats done:
- removed collection.auth and merged it back into the securitySchemes
- changed oauth.flow -> oauth.flows to match the spec
- updated the migration scripts to handle multiple migrations

### Whats Left:
- [ ] live sync (should get a little easier)
- [ ] migration
- [ ] lots of testing 

### Whats pushed:
- handling multiple oauth flows will be done in a follow [up ticket](https://github.com/scalar/scalar/issues/3698), this lays the groundwork for it

2024-11-15 01:26 UTC, amritk commented on packages/oas-utils/package.json
> +    "zod-to-ts": "github:amritk/zod-to-ts#build"
Will switch back to the main package once they merge my PR

2024-11-18 11:13 UTC, hanspagel requested changes
I can add the same oauth type again and again, is that how it’s supposed to be?

<img width="637" alt="Screenshot 2024-11-18 at 12 12 50" src="https://github.com/user-attachments/assets/8bc34370-0db8-4598-aec7-9b35166cf0ad">

2024-11-18 11:15 UTC, hanspagel commented
It shows the authorize URL as a placeholder, but shouldn’t it be the value?

<img width="639" alt="Screenshot 2024-11-18 at 12 14 39" src="https://github.com/user-attachments/assets/312c20f0-9599-495f-9aa8-c8dc7d3c0301">

2024-11-18 17:07 UTC, amritk commented
> I can add the same oauth type again and again, is that how it’s supposed to be?
@hanspagel correct users do have multiple instances of the same type of auth. We should allow them to edit the name but we can do that in a later improvement

I think you are creating a new auth there instead of selecting one from galaxy, everything looks to be prefilled
![image](https://github.com/user-attachments/assets/d43eb698-c2e8-4671-9573-305654572427)

2024-11-19 07:32 UTC, geoffgscott reviewed
Code wise looks good. Untested.

2024-11-19 07:32 UTC, geoffgscott commented on packages/api-client/src/views/Request/RequestSection/RequestAuth/RequestExampleAuth.vue
> +            :modelValue="scheme.username"
:1st_place_medal: 
Love seeing all this live in the scheme

2024-11-19 13:37 UTC, hanspagel approved these changes
Ah, yes. I misunderstood our UI. :)

2024-11-19 18:11 UTC, amritk commented on packages/api-client/src/views/Request/consts/new-auth-options.ts
> +          type: 'clientCredentials',
This is from before, ur right it might not be needed anymore. I can see if it breaks if I remove it

2024-11-19 18:11 UTC, amritk commented on .prettierignore
> -
Decide to let prettier prettify the files 🙂

2024-11-19 19:10 UTC, amritk commented on packages/api-client/src/views/Request/consts/new-auth-options.ts
> +          type: 'clientCredentials',
nvm it is used
```ts
updateScheme(`flows.${flow.type}.token`, '')"
```

2024-11-19 19:19 UTC, marclave approved these changes

2024-11-19 20:11 UTC, merged