style(icons): updates library icon
scalar/scalar pull request #3902
Opened 2024-11-15 17:05 UTC by antlio

this pr updates library icons in order to fix viewbox issue spotted by @cameronrohani  + restyle some of them.

**⊢ collection icon before / after**
<div>
<img width="400" alt="image" src="https://github.com/user-attachments/assets/9ee541e3-fe4c-4034-8faa-c9e21b4e8cef">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/396ffe2e-7884-4f0e-9e30-9020d6829895">
</div>

as i removed some we are not filling up the list anymore, might want to replace them too?

2024-11-15 17:11 UTC, cameronrohani approved these changes

2024-11-15 17:43 UTC, amritk reviewed
will defer to @cameronrohani and @hwkr

2024-11-15 18:14 UTC, cameronrohani commented
almost perfect, just two icons that aren't working with the stroke so we should probably change out

<img width="77" alt="image" src="https://github.com/user-attachments/assets/1033911a-fc32-4e3b-8c28-2b7454803a8a">
<img width="76" alt="image" src="https://github.com/user-attachments/assets/393b51ba-9971-4c83-8e00-5e071a362d32">

2024-11-15 18:16 UTC, cameronrohani requested changes
packages/icons/src/icons/image-picture-flower.svg
packages/icons/src/icons/tag-new-circle.svg

need some tweaks

2024-11-15 19:40 UTC, hwkr requested changes
The icons look good! Thanks for cleaning those up.

I think if we're deleting icons we have the potential to break people's collections though, we probably either need to add a fallback for the library icon or a migration that updates peoples icons.

2024-11-15 19:40 UTC, hwkr commented on packages/icons/src/icons/programming-computer-database-server.svg
I feel like still having a server icon for the user selectable ones would be nice 🤔

2024-11-15 19:40 UTC, hwkr commented on packages/icons/src/icons/shopping-cart.svg
Maybe this should be renamed `shopping-bag` if we're changing how it looks?

2024-11-16 09:00 UTC, antlio commented
> packages/icons/src/icons/image-picture-flower.svg packages/icons/src/icons/tag-new-circle.svg
> 
> need some tweaks

fixed!

2024-11-16 09:07 UTC, antlio commented on packages/icons/src/icons/shopping-cart.svg
revert to cart!

2024-11-16 09:34 UTC, antlio commented on packages/icons/src/icons/programming-computer-database-server.svg
added back

2024-11-16 15:47 UTC, hwkr approved these changes
Look good! 😊

2024-11-19 12:12 UTC, hanspagel approved these changes
Nice update!

2024-11-19 13:32 UTC, merged