feat(Scalar.AspNetCore): support multiple scalar endpoints
scalar/scalar pull request #3907
Opened 2024-11-15 20:49 UTC by xC0dex

This PR introduces support for registering multiple `MapScalarApiReference` endpoints. To achieve this, I decided to clone the options before invoking them in the action. This approach ensures that the options can be invoked multiple times without side effects.

Closes #3901

2024-11-17 09:55 UTC, xC0dex commented on packages/scalar.aspnetcore/src/Scalar.AspNetCore/Extensions/ScalarEndpointRouteBuilderExtensions.cs
> +        var options = endpoints.ServiceProvider.GetService<IOptions<ScalarOptions>>()?.Value is { } existingOptions ? existingOptions with { } : new ScalarOptions();
Hey @alfkonee, thanks for the review! I had the same thought about using named options for each OpenAPI document name. However, during the `MapScalarApiReference` call, we don't know the name of the OpenAPI document. The options are needed to correctly map the endpoint route based on the `EndpointPathPrefix`.

Once Scalar supports multiple API documents, we can revisit this package and refactor it to add/configure OpenAPI documents via the options. At that point, introducing named options may also make sense.

2024-11-17 10:01 UTC, xC0dex commented on packages/scalar.aspnetcore/src/Scalar.AspNetCore/Options/ScalarOptions.cs
> +public sealed record ScalarOptions
I'm not sooo happy with this. I'll rethink this solution.

2024-11-20 13:23 UTC, DaleMckeown commented
@xC0dex Will this also enable Scalar to pull OpenApi specs from remote hosts?

Imagine you have 5 microservices on their own URLs, each exposing an OpenApi spec. Then you have one documentation site that wants to consume all of those OpenApi spec documents and show them in a single scalar UI.

This is possible in Swagger using the `swaggerOptions.SwaggerEndpoint` option, but I can't seem to find anything similar for Scalar.

2024-11-21 10:56 UTC, hanspagel requested changes
This is awesome! Can you add this to the README, too? 🤩

2024-11-21 13:54 UTC, xC0dex commented
I think I'll close this PR and open a new one once I have a suitable solution for it.

2024-11-21 13:54 UTC, closed without merging