feat(api-client): catch OpenAPI parsing errors
scalar/scalar pull request #3954
Opened 2024-11-20 10:26 UTC by hanspagel

Currently, `createClient` and `createApiClientModal` throw an error for invalid OpenAPI documents.

With this PR those errors are catched and a helpful message is printed to the console.

<img width="726" alt="Screenshot 2024-11-20 at 11 22 55" src="https://github.com/user-attachments/assets/ebc40147-3287-44d4-9e88-409adc2b72bc">

2024-11-20 10:26 UTC, hanspagel commented on packages/openapi-parser/src/utils/makeFilesystem.test.ts
> -import { getEntrypoint } from './getEntrypoint'
wasn’t used

2024-11-20 10:59 UTC, tmastrom approved these changes
Nice work!

2024-11-21 07:11 UTC, geoffgscott requested changes
This would be much more streamlined if we just caught the errors as needed in `importSpecFile`

For this particular case i think we should only catch the parsing errors and then log a suitable message to the console using `console.warn`

2024-11-21 09:21 UTC, geoffgscott commented
Closing in favour of https://github.com/scalar/scalar/pull/3969/files

2024-11-21 10:19 UTC, hanspagel commented
Okay, we’ve got something better!

2024-11-21 10:19 UTC, closed without merging