fix: Properly catch and log invalid string parse errors
scalar/scalar pull request #3969
Opened 2024-11-21 09:21 UTC by geoffgscott

Invalid string errors were not being caught properly and causing failures on spec changes. This captures them and assigns an appropriate error message.

2024-11-21 09:47 UTC, antlio approved these changes
@hanspagel will have a better eye but looks like great enhancements to me!

2024-11-21 09:47 UTC, antlio commented on packages/openapi-parser/src/configuration/index.ts
> +  INVALID_CONTENT: 'Unable to parse valid JSON or YAML.',
nit, wdyt about using:

```suggestion
  INVALID_CONTENT: 'Failed to parse content as valid JSON or YAML.',
```

2024-11-21 09:47 UTC, antlio commented on packages/openapi-parser/src/configuration/index.ts
> +  INVALID_CONTENT: 'Unable to parse valid JSON or YAML.',
should we have one error per type at some point?

2024-11-21 09:59 UTC, hanspagel approved these changes
While I think I could also integrate a few of the improvements in the parser, for the specific issue I still prefer #3954.

I think it’s a good thing that `importSpecFile` and `importSpecFromUrl` throw an error that I can then react depending on the use case, e.g. I’d like render the error differently when using the methods in the CLI.

But, if we want to go with this PR here, it needs some work. I’d like to streamline the changes in the parser with the existing code base, and currently we lost the error output for the references. Hmu to discuss this!

<img width="1504" alt="Screenshot 2024-11-21 at 10 51 36" src="https://github.com/user-attachments/assets/510bd660-6412-4a0c-8f0a-d8873cd3ec85">

2024-11-21 10:14 UTC, hanspagel commented
Okay, this is the one we want to get it. But we’ll merge a quick fix first, and I’ll go through this PR here and add to it. ✌️

2024-11-21 10:18 UTC, hanspagel requested changes
Will go through it 👍

2024-11-21 17:31 UTC, amritk approved these changes
Code looks good, did not test

2025-02-21 11:41 UTC, hanspagel commented
This is great, but we need an empty PR queue. I need to pick this up again, after we applied the new formatting.

2025-02-21 11:41 UTC, closed without merging