feat(components): cleanup and extend floating components
scalar/scalar pull request #3984
Opened 2024-11-22 05:06 UTC by hwkr

Updates and cleans up a bunch of the floating components (ScalarFloating, ScalarDropdown etc.). Theres a few small breaking changes in here but since we're the only ones that use `@scalar/components` (and it's semver < 1.0.0) I don't think we should have any problems. That being said a quick test of the client and references never hurt.

Overview of changes:

2024-11-22 07:26 UTC, antlio commented
great great work! 

just spotted the following so far:

<details>
<summary>environment selector out of window</summary>
<img width="400" alt="image" src="https://github.com/user-attachments/assets/b07bab6e-6bdf-4b57-b662-fc1b884e9f78">
</details>


<details>
<summary>command request selector extra gap</summary>
<img width="174" alt="image" src="https://github.com/user-attachments/assets/91f6e500-cbbb-4d24-9a8c-6324f8c68541">
</details>

<details>
<summary>error on sidebar request dropdown click</summary>
```json
Error: Passing props on "template"!
The current component <MenuButton /> is rendering a "template".
However we need to passthrough the following props:
  - aria-controls
  - aria-expanded
  - aria-haspopup
  ```
</details>

<details>
<summary>auth dropdown doesn't open</summary>
```json
index-BeJdfT_j.js:14 TypeError: Cannot read properties of null (reading 'emitsOptions')
  ```
</details>

2024-11-22 19:42 UTC, amritk commented
For some reason I cannot import galaxy into the client (CORS error). Going through the code now

2024-11-22 21:39 UTC, amritk requested changes
Code looks good, tests 👍🏾, docs 👍🏾 

In testing I only found this issue: when you click on the menu button in the sidebar, all of the ellipsis are showing. I think we fixed this before but was re-introduced here

![image](https://github.com/user-attachments/assets/4efd88ac-8e7f-4c77-9ce4-468b39be7d29)

2024-11-22 21:39 UTC, amritk commented on packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
> +        class="absolute inset-0 -z-1 rounded bg-b-1 shadow-lg brightness-lifted" />
whats this div aboot

2024-11-22 21:44 UTC, amritk commented on packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
> +        class="absolute inset-0 -z-1 rounded bg-b-1 shadow-lg brightness-lifted" />
yolo

2024-11-22 21:48 UTC, amritk approved these changes

2024-11-22 21:49 UTC, hwkr commented on packages/api-client/src/views/Environment/EnvironmentVariableDropdown.vue
> +        class="absolute inset-0 -z-1 rounded bg-b-1 shadow-lg brightness-lifted" />
Added a comment

2024-11-23 07:42 UTC, antlio commented
last nit is that is we open a request sidebar menu, and want to open another one, it gets now closed vs swapping as before:

<img width="535" alt="image" src="https://github.com/user-attachments/assets/af3be033-e19b-4843-b855-e4667e253ff0">

2024-11-23 07:44 UTC, antlio approved these changes
great great work - onlly one last non blocking comment

2024-11-25 16:05 UTC, hwkr commented
> last nit is that is we open a request sidebar menu, and want to open another one, it gets now closed vs swapping as before:
> 
> <img alt="image" width="535" src="https://private-user-images.githubusercontent.com/14966155/389182112-af3be033-e19b-4843-b855-e4667e253ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTEwMDgsIm5iZiI6MTczMjU1MDcwOCwicGF0aCI6Ii8xNDk2NjE1NS8zODkxODIxMTItYWYzYmUwMzMtZTE5Yi00ODQzLWI4NTUtZTQ2NjdlMjUzZmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDE2MDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNWYxMWYzNDZlYzUxZTE4ZWZiZGM0MjdjYWU2ZTA1MDRkNGFkYzk2YjYzNzJiMDViZmFmMmM4NGM4MmY2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TKy0JzdrE5rxNKq0DZLRcRoZ79T8hioYRbQe5tKlBL4">

Mmmm okay, I think maybe I'll merge then fix this after

2024-11-26 05:13 UTC, merged