fix(api-client): request params clear action
scalar/scalar pull request #4235
Opened 2024-12-16 20:11 UTC by antlio

this pr update the request params clear action in the api client in order to allow clearance on enabled items, however required items will remain + it adds a tooltip information as seen below:

<img width="441" alt="image" src="https://github.com/user-attachments/assets/c982513a-fc64-4d09-a98c-185fcece49e6" />

2024-12-17 10:24 UTC, hanspagel requested changes
What if we delete the required parameters, if there are only required parameters in the list? 🤔 

Two scenarios:

1) There are only required parameters and I click on clear, I might expect to actually clear the required parameters.

2) There are required and optional parameters, it might be good to only delete the optional parameters. And if someone wants to clear the remaining parameters a second click will delete the remaining parameters.

2024-12-17 10:24 UTC, hanspagel commented on packages/api-client/src/views/Request/RequestSection/RequestParams.vue
> +                <span>Clear all non required parameters</span>
```suggestion
                <span>Clear optional parameters</span>
```

2024-12-17 10:37 UTC, antlio commented
> What if we delete the required parameters, if there are only required parameters in the list? 🤔
> 
> Two scenarios:
> 
> 1. There are only required parameters and I click on clear, I might expect to actually clear the required parameters.
> 2. There are required and optional parameters, it might be good to only delete the optional parameters. And if someone wants to clear the remaining parameters a second click will delete the remaining parameters.

Like I said, the clear action removed all parameters except the required ones - today we only clear the disabled ones

2024-12-17 10:38 UTC, antlio commented on packages/api-client/src/views/Request/RequestSection/RequestParams.vue
> +                <span>Clear all non required parameters</span>
way better!

2024-12-17 10:38 UTC, antlio commented
> 1. There are only required parameters and I click on clear, I might expect to actually clear the required parameters.

should we omit the display in that case?

2024-12-17 13:05 UTC, hanspagel commented
Ah, yes! Got it. Yeah, we can hide the Clear button then?

2024-12-18 16:37 UTC, antlio commented
> Ah, yes! Got it. Yeah, we can hide the Clear button then?

added a function to display clear button only if non required param with key or value are present

2024-12-19 10:29 UTC, hanspagel approved these changes
Sick

2024-12-19 10:29 UTC, merged