This PR addresses [DOC-1330] Allow SEO Customization
scalar/scalar pull request #473
Opened 2023-11-15 17:34 UTC by FotieMConstant

chore(.npmrc): add .npmrc file with auto-install-peers=true
feat(api-reference): add support for metaData configuration in ApiReference component
feat(api-reference): add @unhead/schema and unhead as dependencies in package.json

feat(ApiReference.vue): add support for metaData prop and use it to create global head instance and set SEO meta tags

chore(types.ts): import MetaFlatInput from '@unhead/schema'
feat(types.ts): add metaData property to ReferenceConfiguration type

feat(swagger-parser): add vite.config.ts file for configuring Vite build options

2023-11-15 17:36 UTC, FotieMConstant commented
This PR fixes #473 issue

2023-11-15 17:37 UTC, FotieMConstant commented
This PR fixes #470 issue

2023-11-16 09:00 UTC, hanspagel requested changes
Awesome, thanks for taking the time! We can delete the .npmrc and I’ve added two suggestions to improve the comments. What do you think?

2023-11-16 09:00 UTC, hanspagel commented on packages/api-reference/src/types.ts
> +  /** For metadata */
```suggestion
  /** If used, passed data will be added to the HTML header. Read more: https://unhead.unjs.io/usage/composables/use-seo-meta */
```

2023-11-16 10:46 UTC, FotieMConstant commented on .npmrc
@marclave and i had some issues locally on my end yesterday during a coding session. I equally mentioned there's no need to push this file. just forgot to exclude it, my bad.

2023-11-16 10:49 UTC, FotieMConstant commented
@hanspagel it should be all good now. Thanks for the suggestions

2023-11-20 06:24 UTC, marclave commented
@hanspagel how are the latest changes, seems good from my review. We just gotta tidy up the merge conflicts :)

2023-11-20 10:57 UTC, hanspagel commented
Oh, sorry. @FotieMConstant any chance you could resolve the conflicts? We’ll get this in ASAP then.

2023-11-24 11:13 UTC, merged